### ISSUE TITLE
My world is blue

### ISSUE THREAD

**Issue by qpre** [weijiangan/emacs-snazzy#1]
Hey !

I tried using this theme, but whenever I install and use it, I get this result:

<img width="766" alt="screen shot 2018-01-21 at 12 54 35" src="https://user-images.githubusercontent.com/2156263/35193900-6a9019cc-feaa-11e7-8ca7-19d2f2253737.png">

Do you have any idea of what I could be missing ?

**Comment by weijiangan** [comment]
Hey! Sorry for the late reply for I was on a long vacation. It appears to me you're using some terminal emulator am I correct? Your terminal's color settings might affect it. As far as experience goes, themes don't work great on the terminal Emacs and I'm afraid there's not much that I can do about it unfortunately :\
