### ISSUE TITLE
Links for the example screenshot?

### ISSUE THREAD

**Issue by dngrhm** [weijiangan/emacs-snazzy#2]
Could you add some links in the README to point to other packages you use to get your emacs to look like the screenshot?  More specifically what package/packages do you use to modify you status bar at the bottom?  Thanks for making this an emacs theme!

**Comment by weijiangan** [comment]
Hey! Sorry for the late reply for I was on a long vacation. Yea I will put up more information ASAP but what you are looking for is Powerline with Spaceline theme, which was originally from Spacemacs. And that's pretty much it really. You might also want to Diminish or Delighted mode to shrink the mode names.
